name: Exercise 1

# This is the trigger
on:
    workflow_dispatch:
    schedule:
        - cron: "0 9 * * *"

# This is the job
jobs:
    author_info:
        runs-on: ubuntu-latest
        steps:
            - name: Check out this repo
              uses: actions/checkout@v4 # creates copy of repo in the runner

    - name: Fetch author name from secrets
      env:
        AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
        run: |-
            # Use the author name from secrets, fallback to default if not set
            AUTHOR="${AUTHOR_NAME:-junji+ito}"
            # Replace spaces with + for URL encoding
            AUTHOR_ENCODED=$(echo "$AUTHOR" | sed 's/ /+/g')
            echo "Fetching data for author: $AUTHOR"
            curl -s "https://openlibrary.org/search/authors.json?q=${AUTHOR_ENCODED}" > "$(date +%F)-authors.json"
    
    - name: Commit and push changes
        run: |-
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add *.json
            # Only commit if there are changes
            git diff --staged --quiet || git commit -m "Update author data - $(date +%F)"
            git push