name: Run Pytest 

# This is the trigger
on:
    workflow_dispatch:
    push: 
      branches: [main]
    pull_request: 
      branches: [main]

# This is the job
jobs:
    author_info:
        runs-on: ubuntu-latest
        steps:
            - name: Check out this repo
              uses: actions/checkout@v4 # creates copy of repo in the runner

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
            - name: Run tests
              run: |
                pytest tests/test_calculator.py --verbose
